apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: {{ .Values.servicetype }}
  ports:
    - name: rabbitmq
      port: 5672
    - name: rabbitmq-ui
      port: 15672
      #nodePort: 30000
      #targetPort: 5672
  selector:
    app: rabbitmq